### ISSUE TITLE
gitbook pdf is not searchable

### ISSUE THREAD

**Issue by golflimaechoecho** [puppetlabs/ilt-getting-started-with-puppet-issues#12]
## Use Case
A clear and concise description of what the problem you're trying to solve is. Ex. I'm always frustrated when [...]

The pdf file generated by gitbook does not appear to represent text with normal/printable characters

eg: in puppet-gwsp-082020.pdf from [here|https://puppet.slack.com/files/UF3HT8H89/F01AN8G88F3/puppet-gswp-082020.pdf], attempting to copy the text "Node groups are useful because configuration is applied to many different sub categories of device" on page 31 (Why Node Groups Matter) results in

􏱈􏰔􏰌􏰄 􏰈􏰋􏰔􏰏􏰐􏰗 􏰊􏰋􏰄 􏰏􏰗􏰄􏰕􏰏􏰓 􏰒􏰄􏰚􏰊􏰏􏰗􏰄 􏰚􏰔􏰇􏰤􏰈􏰏􏰋􏰊􏰅􏰆􏰔􏰇 􏰆􏰗 􏰊􏰐􏰐􏰓􏰆􏰄􏰌 􏰅􏰔 􏰛􏰊􏰇􏰟 􏰌􏰆􏰕􏰕􏰄􏰋􏰄􏰇􏰅 􏰗􏰏􏰒 􏰚􏰊􏰅􏰄􏰈􏰔􏰋􏰆􏰄􏰗 􏰔􏰕 􏰌􏰄􏰘􏰆􏰚􏰄􏰡

This also means the pdf cannot be searched for words/phrases; as there is also no table of contents, this means to find information in the document, you need to scroll through until you find it - not ideal for a document that runs to 300+ pages.

## Describe the Solution You Would Like

Gitbook should generate PDF file with usable characters that can be searched/copied.

**Comment by josephoaks** [comment]
Watermarking of the PDF obscures the text to prevent copy of the content.
Table of Content, thank you for pointing this out. We will have to make an actual TOC page to compensate that the page does not get created correctly.
