### ISSUE TITLE
Download page is missing, labs still refer to it. Git Clone may not be a good replacement

### ISSUE THREAD

**Issue by sooyean-hoo** [puppetlabs/ilt-getting-started-with-puppet-issues#13]
Download page is missing.   Now it is compensated by having the resources in the gitlab which is associated with the Class. However the labs in the course is not adapted for the use with the new setup: GitLab. 

Some of the labs are using the original method of downloading the resources. Hence this causes some confusion for the students when they are doing the lab, esp so for novices (who are most of the students for GSWP)

Update: As there is no instruction on how to git clone the download repo, Some Students does not know how to git-clone the repo, as most may have not even seen git before.

**Comment by josephoaks** [comment]
Fixed
