### ISSUE TITLE
Lab 2.2 Missing a statement to ask students to switch btw Linux and Windows. 

### ISSUE THREAD

**Issue by sooyean-hoo** [puppetlabs/ilt-getting-started-with-puppet-issues#15]
= Lab 2.2 Missing a statement to ask students to switch btw Linux and Windows. Without the switching over, the lab will have error. The student will have error for starting a time server which is already running for both Windows and Linux.

**Comment by josephoaks** [comment]
Added a callout to tell them to switch.
