### ISSUE TITLE
Lab 6.2  Can we have the git clone below in 1 line?

### ISSUE THREAD

**Issue by sooyean-hoo** [puppetlabs/ilt-getting-started-with-puppet-issues#16]
= Lab 6.2 
Can we have the git clone below in 1 line? 
As it is displayed as 2 line,  the student assume that as 2 separate commands:
"git clone" & "git@gitlab.classroom.puppet.com:puppet/downloads.git"

From reading the potion in the Lab
"
2. Clone the downloads repo 
git clone 
git@gitlab.classroom.puppet.com:puppet/downloads.git
Create the Facter location:
"

**Comment by josephoaks** [comment]
Instructions were cleaned up.
