### ISSUE TITLE
Lab 7.1 Missing statement to ask Student to work on only 1 platform Windows or Linux not both...

### ISSUE THREAD

**Issue by sooyean-hoo** [puppetlabs/ilt-getting-started-with-puppet-issues#17]
= Lab 7.1 Missing statement to ask Student to work on only 1 platform Windows or Linux not both... There will be conflict otherwise.
Also instruction for Linux should only asks student to Pin Linux box only to node group, as the module used with that group is “ntp”, instead of stating that Windows Box is an pinned candidate too.   This is likewise for the Windows lab, as Linux box cannot use winntp.

**Comment by josephoaks** [comment]
The instructions clearly state "On the Rules tab, you need to add your hosts to your node group. At the bottom of the window, there is an option to Pin specific nodes to the group. Click the field labeled Node name. In the dropdown, **select either your Linux or Windows machine and click Pin node**."

Added a callout stating if they pin both nodes they will get an error, which is expected.
