### ISSUE TITLE
Lab 8.1 Under the Optional Lab for the Linux Section, 

### ISSUE THREAD

**Issue by sooyean-hoo** [puppetlabs/ilt-getting-started-with-puppet-issues#18]
=Lab 8.1 Under the Optional Lab for the Linux Section, There is no mention of "switching" to the StudentN branch.. so the Student are confused when they did not the see the code which they did in Linux, in Windows via VSCode. They saw a empty folder : the master branch.

**Comment by josephoaks** [comment]
Thank you, added an extra step to switch to their StudentN branch.
