### ISSUE TITLE
= Lab 10.1 Windows Lab,  The prompt remain the same, even after a "cd C:/Users/Administrator/control-repo/site/role" is run. This makes the students very confused.

### ISSUE THREAD

**Issue by sooyean-hoo** [puppetlabs/ilt-getting-started-with-puppet-issues#19]
= Lab 10.1 Windows Lab,  The prompt remain the same, even after a "cd C:/Users/Administrator/control-repo/site/role" is run. This makes the students very confused.

**Comment by zoojar** [comment]
I understand the reason behind this is to reduce line length.  I too have had students experience this unnecessary confusion.

**Comment by josephoaks** [comment]
Fixed, we removed all command prompt PS1 references.
This is something that has been a trouble issue for years, how do we show this without having massively long lines, do we show the, do we not show them. We just removed all references to the PS1 and made the commands fully qualified if they contain paths.
