### ISSUE TITLE
Lab 12.1 Windows Lab,  Under " Add a smoke test (Optional) Add the example file to allow local puppet apply testing: In Visual Studio Code, right click site. Click profile. Click New Folder and name it examples"

### ISSUE THREAD

**Issue by sooyean-hoo** [puppetlabs/ilt-getting-started-with-puppet-issues#20]
= Lab 12.1 Windows Lab,  Under " Add a smoke test (Optional)
Add the example file to allow local puppet apply testing:
In Visual Studio Code, right click site. Click profile. Click New Folder and name it examples"

This creates an "examples" folder under "control-repo/site", instead of under "control-repo/site/profile". This will come back to haunt the people with an error message, for the smoke test.

This lab also plagued by the same confusing as Lab 10.1 for the prompt.

**Comment by josephoaks** [comment]
A file structure example was created to show the file paths
control-repo
|_site
  |_role
    |_examples
      |_bastion.pp
