### ISSUE TITLE
= Lab 15.1 First, this is lab 15, but we are using lab14 resources: namesake wise. This causes confusion.

### ISSUE THREAD

**Issue by sooyean-hoo** [puppetlabs/ilt-getting-started-with-puppet-issues#21]
= Lab 15.1
First, this is lab 15, but we are using lab14 resources: namesake wise. This causes confusion.
Second, there is no "Downloads page on the presentation", so the user are confused again.   Students usually follow the lab, then learn from the results. So extra time, efforts and patience is needed to get them the results, when such eventualities occur.

"Create the operating system-specific profiles
Within the control-repo/site/profile/manifests folder, create a new folder called sample_app
The contents of the Linux and Windows manifests can be found in the Downloads page on the presentation for this module. Download lab14_linux.pp and lab14_windows.pp to your student machine."

**Comment by josephoaks** [comment]
Yes thanks for pointing this out, we will get these renamed!

**Comment by josephoaks** [comment]
Fixed
