### ISSUE TITLE
= Labs for Windows, Involving VSCode, can we have some screenshots to be show the place to click for instruction, instead of convoluted description: a picture is worth a thousand words.

### ISSUE THREAD

**Issue by sooyean-hoo** [puppetlabs/ilt-getting-started-with-puppet-issues#22]
= Labs for Windows, Involving VSCode, can we have some screenshots to be show the place to click for instruction, instead of convoluted description: a picture is worth a thousand words. 
E.g.
Lab 8.1 Windows:  "Select the ellipsis to the right of", not many people know what is a "ellipsis". Even among programmers, such those who are in the know, are rare.

Lab 10.1 Windows:  "click the source control icon on the left menu", Most System Administrators do not use source control during their whole career, so they would not know what is a source control, let alone its icon.

Lab 10.1 Windows:  "Click the check mark at the top to commit the changes."    ''check mark' is not very descriptive in some part of the whole, some people just call it a "tick"

**Comment by josephoaks** [comment]
@sooyean-hoo

I would normally agree 100% with this statement a picture is worth a thousand words, and we used to have images for VS Code, however VS Code changes regularly causing the images to be outdated quite regularly, hence when opted to go for wording instead. Even then however with the last update, they have even changed some of the wording, no win situation...

As to the "ellipsis" we can change that to reference the '...' or the vertical version

Thoughts?

**Comment by sooyean-hoo** [comment]
I find myself agreeing and also disagreeing on your points made:
===="VS Code changes regularly causing the images to be outdated quite regularly" : Yes I agree, but...
Also a point to note, we control the environment(the Windows version is fixed at our choosing), the pdk is also fixed at our choosing, these apply to most of the software used in the lab. Hence it is safe that we choose which version of VS Code and the puppet plugins which we are using. In fact, there is no step to upgrade them to the latest prior to the lab propers. Hence all the icons and position of the icons should be known to us beforehand. It is just that, if there is a decision to update the VS Code's version, those included screenshots will have to update accordingly. This is more like a controlled chaos, than an uncontrolled one. Maybe I am wrong.... Your Thoughts?

===="when opted to go for wording instead": Partially. 
I believe that a screenshot of just the button should be sufficient, at the bare minimum. At least we let the student knows what kind of buttons are they going to look for.     Wordings is just subjected to their level of familiarity with the technology involved and command of English.



 ===="ellipsis" we can change that to reference the '...', : I am 100% agree on this...This Is a better and easier description for the students  understand.

**Comment by josephoaks** [comment]
Added screenshots and added ("...") to the end of the word ellipsis for clarification.
