### ISSUE TITLE
= Slides for "Why Add Adbstraction?" has mis-spelt the word abstraction as "Adbstraction".

### ISSUE THREAD

**Issue by sooyean-hoo** [puppetlabs/ilt-getting-started-with-puppet-issues#23]
= Slides for "Why Add Adbstraction?" has mis-spelt the word abstraction as "Adbstraction". Even though this brings an artistic take on the word, it seems to be more of hindrance, the students may take this as a word play. The reasons for this, is due the multiple occurrences of the mis-spellings: the previous page  and the said page.

**Comment by josephoaks** [comment]
![Screen Shot 2020-09-18 at 3 07 18 PM](https://user-images.githubusercontent.com/14297130/93645143-a675da80-f9c0-11ea-96a2-1c5f1ac29f32.png)
I'm unsure on this, I searched and do not see Abstraction mis-spelled...

**Comment by sooyean-hoo** [comment]
No worry, I saw this error still exists when I was teaching GSWP starting Sep 8, 2020. Anyway I just checked, all are well.. Thanks
