### ISSUE TITLE
Can we have a page to explain how to create an inventory with encrypted passwords and how to use it with bolt?

### ISSUE THREAD

**Issue by sooyean-hoo** [puppetlabs/ilt-getting-started-with-puppet-issues#24]
Can we have a page to explain how to create an inventory with encrypted passwords and how to use it with bolt? Something which we can direct the students to follow. 
This is one of the most commonly requested documentation during the GSWP lessons.

i.e. ==============from=============

  config:
    transport: winrm
    winrm:
      ssl: false
      user: administrator
      password: Puppetlabs!
- name: linux

==============to=============

  config:
    transport: winrm
    winrm:
      ssl: false
      user: administrator
      password:
        _plugin: pkcs7
        encrypted_value: |
          ENC[PKCS7,MIIBeQYJKoZIhvcNAQcDoIIBajCCAWYCAQAxggEhMIIBHQIBADAFMAACAQEw
          DQYJKoZIhvcNAQEBBQAEggEAPKj7rlAWAaPj+fVwLh14mtgbQwfCJX2UgUBr
          QJ2g8FRh/I589BYlcOZamWxMj7SJyebEtW5utHrp+p7x0gG8z201sbV1Fwi5
          GFvs0Ntr+jDx7SMxViF8d0M4H0kuGWHvHGsly5RTtJiFaIxU7gk19G6OSEBM
          MQI86aCrwTPSF+saxM45H7dJvz6UEyd4yp4Wh2eMXyduZUROcyRUOcyHbThs

**Comment by josephoaks** [comment]
Great suggestion, added.
