### ISSUE TITLE
=Lab 15.1  This is discovered by the Students..... There is no "download of lab14_windows.pp" , but 2 of "cp ~/downloads/lab14_linux.pp ..."

### ISSUE THREAD

**Issue by sooyean-hoo** [puppetlabs/ilt-getting-started-with-puppet-issues#25]
=Lab 15.1  This is discovered by the Students.....
There is no "download of lab14_windows.pp" , but 2 of "cp ~/downloads/lab14_linux.pp ..."

3. Copy ~/downloads/lab14_linux.pp to the control-repo/site/profile/manifests/sample_app folder in your control repo, and rename the file to linux.pp.
cp ~/downloads/lab14_linux.pp ~/control-repo/site/profile/manifests/sample_app/linux.pp

4. Copy ~/downloads/lab14_windows.pp to the control-repo/site/profile/manifests/sample_app folder in your control repo, and rename the file to windows.pp.
cp ~/downloads/lab14_linux.pp ~/control-repo/site/profile/manifests/sample_app/linux.pp

5.Create the control-repo/site/profile/files directory.

**Comment by josephoaks** [comment]
Fixed in current release also updated to match the correct lab number now.
