### ISSUE TITLE
=Lab 6.2 "Clone the downloads repo git clone"  does not work.

### ISSUE THREAD

**Issue by sooyean-hoo** [puppetlabs/ilt-getting-started-with-puppet-issues#26]
=Lab 6.2 "Clone the downloads repo git clone"  does not work.

[centos@2314nix0 tmp]$ git clone git@gitlab.classroom.puppet.com:puppet/downloads.git
Cloning into 'downloads'...
GitLab: The project you were looking for could not be found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
[centos@2314nix0 tmp]$ git clone https://gitlab.classroom.puppet.com/puppet/downloads.git
Cloning into 'downloads'...
fatal: unable to access 'https://gitlab.classroom.puppet.com/puppet/downloads.git/': Issuer certificate is invalid.

[centos@2314nix0 tmp]$ git clone git@gitlab.classroom.puppet.com:puppet/downloads.git
Cloning into 'downloads'...
GitLab: The project you were looking for could not be found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
[centos@2314nix0 tmp]$

**Comment by josephoaks** [comment]
This was fixed in the code.
