### ISSUE TITLE
Update to a current Puppet Enterprise version

### ISSUE THREAD

**Issue by jessereynolds** [puppetlabs/ilt-getting-started-with-puppet-issues#29]
## Use Case

There are many new features and bug fixes in the latest PE as compared to the 2019.2.2 version that is currently running in the classroom, including improvements to the user interface. 2019.2 came out over 12 months ago (6 Nov 2019). It would make sense to be showing students the latest and greatest PE so they get the most positive experience of our trainings, and so they are more motivated to upgrade their own environments. 

## Describe the Solution You Would Like

Upgraded the classroom to PE 2019.8.x.

**Comment by jessereynolds** [comment]
Note I am happy to upgrade the environment but it would be good to get some insight from other trainers about if that's likely to work fine, or cause issues for students with mismatched instructions, or changed / deprecated features in the product.

**Comment by martezr** [comment]
The environment is being updated to PE 2019.8.4 this week. The UI changes require both GSWP and Practitioner to be updated extensively to ensure that the instructions and any screenshots align with the changes.

**Comment by martezr** [comment]
The PE 2019.8.4 version of Puppet Enterprise has been deployed to all future classes of GSWP and Practitioner.

**Comment by jessereynolds** [comment]
🎉
