### ISSUE TITLE
Include open source puppet versions in cert signing slide

### ISSUE THREAD

**Issue by jessereynolds** [puppetlabs/ilt-getting-started-with-puppet-issues#30]
## Use Case

In Lesson 5, "Registering the Agent with the Puppet Server", the old "puppet cert" and new "puppetserver ca" commands are both given and only refer to the PE versions. Many open source users pay for our training also so it would make sense to include that this was a change made in Puppet 6, in addition to the PE version info. 

## Describe the Solution You Would Like

* Change "On the Puppet server (Puppet Enterprise 2018.1)" to "On the Puppet server (Puppet Enterprise 2018.1, puppet 5 and below)"
* Change "On the Puppet server (Puppet Enterprise 2019.x)" to "On the Puppet server (Puppet Enterprise 2019.x, puppet 6 and above)"

**Comment by josephoaks** [comment]
fixed
