### ISSUE TITLE
Consuming Hiera Data - says LTS only has hiera function not lookup

### ISSUE THREAD

**Issue by jessereynolds** [puppetlabs/ilt-getting-started-with-puppet-issues#31]
https://puppet-kmo.gitbook.io/gswp/-MFBOrY4wkT-M5izoA2y/table-of-contents/lesson-11-data-separation/consuming-hiera-data

Slide says 'lookup' is not available in the current LTS and you have to use 'hiera'. This is not true - just change the language to talk about versions of puppet / PE where the lookup() function was introduced.

See also https://github.com/puppetlabs/ilt-practitioner-issues/issues/51

**Comment by josephoaks** [comment]
fixed
