### ISSUE TITLE
Lesson 4 checkpoint has no link

### ISSUE THREAD

**Issue by dylanratcliffe** [puppetlabs/ilt-getting-started-with-puppet-issues#37]
https://puppet-kmo.gitbook.io/gswp/-MPdvCznVUozaZlHS_Hd/table-of-contents/lesson-4-introduction-to-declarative-puppet/checkpoint#time-to-play-a-game

![Screenshot 2021-01-28 at 11 46 24 am](https://user-images.githubusercontent.com/8799341/106134454-76082f00-615e-11eb-8dcd-f8470d80dd7d.png)

**Comment by sooyean-hoo** [comment]
I gave up.. at this point, I just fire up my Kahoot main game on my screen...  
Cos the one before this.. is ways worse.. It ask the student to install the Handphone App.....  By the time, they get that installed,  it is already 1 day gone.

Anyway there is no page with links to Kahoot, like the one in the training videos....

My Checkpoint for Lesson 1.... as of   2nd Mar 2021
 
![image](https://user-images.githubusercontent.com/60423341/109648704-e78c3080-7b95-11eb-9209-11a4b126d3ea.png)

**Comment by dylanratcliffe** [comment]
Checkpoint now has a link. Will create a new ticket for the fact that we should mention that there is a web version too
